# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            # activate different ways to authenticate
            oauth:
              resource_owners:
                my_github: "/login/check-github"
              login_path: /login
              use_forward: false
              failure_path: /login

              oauth_user_provider:
                service: hwi_oauth.user.provider

            #http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
      #require ROLE_ADMIN for /admin*
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
